-- STEP 3: real salons import. Paste ALL of this in Supabase -> SQL Editor -> New query -> Run.
-- 1) adds latitude/longitude columns
-- 2) removes the 18 fictional demo salons
-- 3) adds your 5 real salons (safe to run again)

alter table public.salons add column if not exists lat numeric;
alter table public.salons add column if not exists lng numeric;

delete from public.salons where id in ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18');

insert into public.salons (id,name,tagline,image,gallery,locality,area,distance_km,rating,review_count,starting_price,services,open_hours,is_open,phone,whatsapp,website,address,about,tags,lat,lng) values
('zazzle-indiranagar','Zazzle Salon - Indira Nagar','Unisex salon and bridal studio',NULL,'[]'::jsonb,'12th Main Road, HAL 2nd Stage','Indiranagar',NULL,4.8,3311,NULL,'[{"name": "Haircut", "price": null, "duration": ""}, {"name": "Hair Spa", "price": null, "duration": ""}, {"name": "Hair Colour", "price": null, "duration": ""}, {"name": "Facial", "price": null, "duration": ""}, {"name": "Manicure", "price": null, "duration": ""}]'::jsonb,'{"Mon": "10:00-21:00", "Tue": "10:00-21:00", "Wed": "10:00-21:00", "Thu": "10:00-21:00", "Fri": "10:00-21:00", "Sat": "10:00-21:00", "Sun": "10:00-21:00"}'::jsonb,true,'+91 73538 11111',NULL,'https://zazzlesalon.com/','1082, 12th Main Road, HAL 2nd Stage, Indiranagar 2nd Stage, Bengaluru, Karnataka 560008','A unisex salon and bridal studio offering hair styling, hair spa, haircut and colour, plus skin, nail and makeup services.','["Unisex", "Hair", "Bridal", "Hair Colour", "Hair Spa", "Makeup"]'::jsonb,NULL,NULL),
('toni-and-guy-indiranagar','TONI&GUY Bengaluru Indira Nagar','Professional hair and beauty salon',NULL,'[]'::jsonb,'12th Main, 80 Feet Road, 7th Cross','Indiranagar',NULL,4.3,1779,95,'[{"name": "Senior Stylist Men''s Cut", "price": 714, "duration": "1 hr"}, {"name": "Senior Stylist Women''s Haircut", "price": 1143, "duration": "1 hr 15 min"}, {"name": "Beard", "price": 286, "duration": "20 min"}, {"name": "Threading", "price": 95, "duration": "15 min - 1 hr"}]'::jsonb,'{"Mon": "10:00-21:30", "Tue": "10:00-21:30", "Wed": "10:00-21:30", "Thu": "10:00-21:30", "Fri": "10:00-21:30", "Sat": "10:00-21:30", "Sun": "10:00-21:30"}'::jsonb,true,'+91 97390 60171',NULL,'https://toniandguy.com/pages/indirangar','1st Floor, 618, 12th Main, 80 Feet Rd, near New Empire Restaurant, 7th Cross, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560008','A unisex salon offering haircuts, colour, smoothening, keratin, hair botox, beard styling and makeup services.','["Unisex", "Haircut", "Hair Colour", "Keratin", "Smoothening", "Beard"]'::jsonb,NULL,NULL),
('vurve-indiranagar','Vurve Salon | Indira Nagar','Premium salon for hair, skin and beauty',NULL,'[]'::jsonb,'12th Main Road, Icon Mall','Indiranagar',NULL,4.7,4001,NULL,'[{"name": "Haircut", "price": null, "duration": ""}, {"name": "Hair Colour", "price": null, "duration": ""}, {"name": "Makeup", "price": null, "duration": ""}, {"name": "Nail Art", "price": null, "duration": ""}, {"name": "Lash Services", "price": null, "duration": ""}]'::jsonb,'{"Mon": "10:00-21:00", "Tue": "10:00-21:00", "Wed": "10:00-21:00", "Thu": "10:00-21:00", "Fri": "10:00-21:00", "Sat": "10:00-21:00", "Sun": "10:00-21:00"}'::jsonb,true,'+91 63618 53851',NULL,'https://vurvesalon.com/salon/bangalore-indiranagar/','1st Floor, Icon Mall, 2981, 12th Main Road, Indiranagar, Bengaluru, Karnataka 560008','A premium salon in Indiranagar offering bespoke hair, skin, makeup, lash and nail services, including bridal and self-care treatments.','["Premium", "Hair", "Skin", "Makeup", "Lashes", "Nails", "Bridal"]'::jsonb,NULL,NULL),
('bodycraft-indiranagar','Bodycraft Salon & Spa - Indiranagar','Premium salon, spa and beauty services',NULL,'[]'::jsonb,'100 Feet Road, Defence Colony','Indiranagar',NULL,NULL,0,250,'[{"name": "Men''s Haircut", "price": 700, "duration": "20-30 min"}, {"name": "Barbering", "price": 350, "duration": "15-20 min"}, {"name": "Hair Colour", "price": 250, "duration": ""}, {"name": "Women''s Haircut", "price": 1050, "duration": ""}, {"name": "Global Colour", "price": 2450, "duration": ""}, {"name": "Hair Smoothening", "price": 6000, "duration": ""}]'::jsonb,'{"Mon": "09:00-21:30", "Tue": "09:00-21:30", "Wed": "09:00-21:30", "Thu": "09:00-21:30", "Fri": "09:00-21:30", "Sat": "09:00-21:30", "Sun": "09:00-21:30"}'::jsonb,true,'+91 73539 27916',NULL,'https://www.bodycraft.co.in/location-salon/bengaluru/spa-and-salon-in-indiranagar','#653, 100 Feet Road, Opposite Karachi Bakery, Defence Colony, Indiranagar, Bengaluru, Karnataka 560038','A premium salon and spa offering hair, skin, body, grooming, nail, waxing and pre-bridal services in Indiranagar.','["Premium", "Hair", "Spa", "Skin", "Nails", "Grooming", "Bridal"]'::jsonb,NULL,NULL),
('bounce-indiranagar','Bounce Salon & Spa, Indiranagar','Hair, beauty and spa salon',NULL,'[]'::jsonb,'12th Main, HAL 2nd Stage','Indiranagar',NULL,4.6,2925,NULL,'[{"name": "Haircut", "price": null, "duration": ""}, {"name": "Hair Colour", "price": null, "duration": ""}, {"name": "Hair Spa", "price": null, "duration": ""}, {"name": "Manicure", "price": null, "duration": ""}, {"name": "Facial", "price": null, "duration": ""}]'::jsonb,'{"Mon": "10:00-20:00", "Tue": "10:00-20:00", "Wed": "10:00-21:00", "Thu": "10:00-21:00", "Fri": "10:00-21:00", "Sat": "10:00-21:00", "Sun": "10:00-21:00"}'::jsonb,true,'+91 89258 36675',NULL,'https://www.bouncehere.com/bengaluru/indiranagar','II Floor, No. 610, 12th Main, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038','A salon and spa focused on customised haircuts and colour, with nail, skin, grooming, beauty and spa services.','["Hair", "Colour", "Nails", "Skin", "Grooming", "Beauty", "Spa"]'::jsonb,12.9705121,77.6452835)
on conflict (id) do update set
  name=excluded.name, tagline=excluded.tagline, image=excluded.image, gallery=excluded.gallery, locality=excluded.locality, area=excluded.area, rating=excluded.rating, review_count=excluded.review_count, starting_price=excluded.starting_price, services=excluded.services, open_hours=excluded.open_hours, phone=excluded.phone, whatsapp=excluded.whatsapp, website=excluded.website, address=excluded.address, about=excluded.about, tags=excluded.tags, lat=excluded.lat, lng=excluded.lng;
